workspace:
  base: /rspamd

pipeline:

  build:
    image: gcc
    commands:
      - pwd
      - set -e
      - apt-get update -qq
      - apt-get install -qq cmake libevent-dev libglib2.0-dev libicu-dev libluajit-5.1-dev libmagic-dev libsqlite3-dev libssl-dev ragel libunwind-dev libunwind8
      - umask 0000
      - cmake /rspamd/src/github.com/rspamd/rspamd/ -DDBDIR=/nana -DENABLE_COVERAGE=ON -DENABLE_LIBUNWIND=ON -DCMAKE_INSTALL_PREFIX=/rspamd/install
      - make install -j`nproc`

  rspamd-test:
    image: gcc
    commands:
      - set -e
      - apt-get update -qq
      - apt-get install -qq cmake libevent-dev libglib2.0-dev libicu-dev libluajit-5.1-dev libmagic-dev libsqlite3-dev libssl-dev ragel libunwind-dev libunwind8
      - cd /rspamd/build
      - make rspamd-test -j`nproc`
      - set +e; test/rspamd-test -p /rspamd/lua; echo "export RETURN_CODE=$?" >> $BASH_ENV