workspace:
  base: /rspamd

pipeline:

  build:
    image: rspamd/ci-ubuntu-build
    group: build
    commands:
      - env
      - mkdir /rspamd/build /rspamd/install
      - cd /rspamd/build
      - cmake /rspamd/src/github.com/rspamd/rspamd -DENABLE_COVERAGE=ON -DENABLE_LIBUNWIND=ON -DCMAKE_INSTALL_PREFIX=/rspamd/install
      - ncpu=$(getconf _NPROCESSORS_ONLN)
      - make -j $ncpu install
      - make -j $ncpu rspamd-test

  eslint:
    image: node:latest
    group: build
    commands:
      - npm install
      - ./node_modules/.bin/eslint -v && ./node_modules/.bin/eslint ./
