name: ci

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  linters:
    uses: ./.github/workflows/ci_linters.yml

  fedora:
    uses: ./.github/workflows/ci_rspamd.yml
    with:
      image: ghcr.io/fatalbanana/gha-images:fedora-ci
      name: fedora-ci

  ubuntu:
    uses: ./.github/workflows/ci_rspamd.yml
    with:
      image: ghcr.io/fatalbanana/gha-images:ubuntu-ci
      name: ubuntu-ci
